spring:
    datasource:
      url: "jdbc:mysql://localhost/library" #내 컴퓨터(localhost의 library database를 사용하겠다)
      username: "root"
      password: "1234"
      driver-class-name : com.mysql.cj.jdbc.Driver  #접근할 때 사용할 프로그램
